### ISSUE TITLE
How do I download this?

### ISSUE THREAD

**Issue by Azkuzku** [Roboron3042/SteamControllerSinger#1]
Why do GitHub users never give instructions to download their stuff? It annoys me so much that I'm struggling not to smash my keyboard to pieces right now.

**Comment by different55** [comment]
Maybe you should take some anger management classes then. The downloads are located where all GitHub downloads are, in the releases.

**Comment by Roboron3042** [comment]
Releases are in the releases section, as always on GitHub https://github.com/Roboron3042/SteamControllerSinger/releases
