### ISSUE TITLE
"No device found"

### ISSUE THREAD

**Issue by roopekoo** [Roboron3042/SteamControllerSinger#2]
Hi, a few months ago I tried your fork with a success. All she midi files played as they should have in my steam controller.
But now when I tried to use it once again it just says "No device found".
The controller works normally with wired or wireless mode with or without Steam running but SteamControllerSinger cannot find it.
I have tried to roll back the firmware without any success.
Can you help me? Is this fork even active anymore?

**Comment by vellfire** [comment]
Not sure if the forks active anymore but on the latest firmware, it works fine but only under these conditions:

- Run as root
- Steam Controller is plugged in via USB

I do not have Steam installed and am using the Steam Controller's kernel driver on Gentoo (zen-sources).

**Comment by Maetel1309** [comment]
Works perfectly on windows 7 but not windows 10

**Comment by Roboron3042** [comment]
As of 21/08/2020 it is still working. Tested with:

- Controller plugged in via USB.
- Steam closed.
- OS: Arch Linux

No need for root in my case. 

> Works perfectly on windows 7 but not windows 10

Also I remember everyone that this fork was made to solve the problem of SCS stopping playback after 5 seconds, which was occurring on Linux-based systems at least. This fork won't solve the problem of SCS not working at all on Windows 10, or any version of Windows.
