### ISSUE TITLE
No executable

### ISSUE THREAD

**Issue by matiko13** [Roboron3042/SteamControllerSinger#3]
There is no executable file.

**Comment by Roboron3042** [comment]
Hello, @matiko13 
In case it is your first time using GitHub, you can find executable files in the releases page: https://github.com/Roboron3042/SteamControllerSinger/releases/
In case you aren't a GNU/Linux user: Sorry! No executables are provided for Microsoft Windows. Read the top of the README (I just updated it) for more info ^.^
